# Generated by Django 4.1.1 on 2022-10-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalBackend', '0002_alter_paciente_medico_alter_paciente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='registro',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
